---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: bucket-job
data:
  NAMESPACE: openshift-adp
  OBJECTBUCKETCLAIM: oadp
  DATAPROTECTIONAPPLICATION: velero-sample
  BACKUPSTORAGELOCATION: velero-sample-1
