---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-adp

resources:
  - configmap.yaml
  - dataprotectionapplication.yaml
  - job.yaml
  - objectbucketclaim.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloud-credentials
    files:
      - secrets/cloud