---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bucket-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: bucket-job
subjects:
  - kind: ServiceAccount
    name: bucket-job
    namespace: openshift-adp
