---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-adp

bases:
  - github.com/redhat-cop/gitops-catalog/openshift-api-for-data-protection-operator/overlays/stable
